name: CI
on: [push]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5
      - uses: php-actions/phpunit@v2
        with:
          bootstrap: vendor/autoload.php
          configuration: tests/OperacionesTest.php
       